config/routes.rb
# frozen_string_literal: true

# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                                  root GET    /                                                                                        redirect(301, /pipelines)
#                               secrets GET    /secrets(.:format)                                                                       secrets#index
#                                       POST   /secrets(.:format)                                                                       secrets#create
#                            new_secret GET    /secrets/new(.:format)                                                                   secrets#new
#                           edit_secret GET    /secrets/:id/edit(.:format)                                                              secrets#edit
#                                secret GET    /secrets/:id(.:format)                                                                   secrets#show
#                                       PATCH  /secrets/:id(.:format)                                                                   secrets#update
#                                       PUT    /secrets/:id(.:format)                                                                   secrets#update
#                                       DELETE /secrets/:id(.:format)                                                                   secrets#destroy
#                       check_pipelines GET    /pipelines/check(.:format)                                                               pipelines#check
#                             pipelines GET    /pipelines(.:format)                                                                     pipelines#index
#                                       POST   /pipelines(.:format)                                                                     pipelines#create
#                          new_pipeline GET    /pipelines/new(.:format)                                                                 pipelines#new
#                         edit_pipeline GET    /pipelines/:id/edit(.:format)                                                            pipelines#edit
#                              pipeline GET    /pipelines/:id(.:format)                                                                 pipelines#show
#                                       PATCH  /pipelines/:id(.:format)                                                                 pipelines#update
#                                       PUT    /pipelines/:id(.:format)                                                                 pipelines#update
#                                       DELETE /pipelines/:id(.:format)                                                                 pipelines#destroy
#                          run_pipeline GET    /pipelines/:id/run(.:format)                                                             pipelines#run
#                              show_run GET    /pipelines/:id/runs/:run_id(.:format)                                                    runs#show
#                                  runs GET    /runs(.:format)                                                                          runs#index
#                                       POST   /runs(.:format)                                                                          runs#create
#                               new_run GET    /runs/new(.:format)                                                                      runs#new
#                              edit_run GET    /runs/:id/edit(.:format)                                                                 runs#edit
#                                   run GET    /runs/:id(.:format)                                                                      runs#show
#                                       PATCH  /runs/:id(.:format)                                                                      runs#update
#                                       PUT    /runs/:id(.:format)                                                                      runs#update
#                                       DELETE /runs/:id(.:format)                                                                      runs#destroy
#                           destroy_run DELETE /pipelines/:id/runs/:run_id(.:format)                                                    runs#destroy
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  root to: redirect('/pipelines')
  resources :secrets
  get '/pipelines/check', to: 'pipelines#check', as: 'check_pipelines'
  resources :pipelines
  get '/pipelines/:id/run', to: 'pipelines#run', as: 'run_pipeline'
  get '/pipelines/:id/runs/:run_id', to: 'runs#show', as: 'show_run'
  get '/pipelines/:id/runs/:run_id/output', to: 'runs#output', as: 'show_run_output'
  resources :runs
  delete '/pipelines/:id/runs/:run_id', to: 'runs#destroy', as: 'destroy_run'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pipeline.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: pipelines
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  repo       :string
#  triggers   :string
#  domain     :string
#
class Pipeline < ApplicationRecord
  has_many :runs, dependent: :destroy, foreign_key: 'pipeline_id'

  validates :name, presence: true
  validates :repo, presence: true,
    format: {
      with: /git\@(.*).git/,
      message: 'please enter a valid git repository using a ssh url'
    }

  scope :with_triggers, -> { where('triggers IS NOT NULL') }

  def average_duration_seconds
    durations = runs.limit(64)
      .map(&:duration_seconds)
      .compact

    return 0 if durations.empty?

    seconds = durations.inject { |sum, el| sum + el }.to_f / durations.size

    # NOTE: Sanity check for outliers; build should certainly finish
    # before one hour elapses.
    return 0 if seconds > 60 * 60

    seconds
  end

  def pretty_average_duration
    if average_duration_seconds.nil? || average_duration_seconds.zero?
      ''
    else
      minutes = (average_duration_seconds / 60).floor
      seconds = (average_duration_seconds % 60).round
      "#{minutes}m #{seconds}s"
    end
  end

  def pretty_activity(days: 7)
    runs_per_day = (0..days).to_a.reverse.
      map do |num|
        day = DateTime.now.days_ago(num)
        runs.where(
          'created_at < ? AND created_at > ?', day.end_of_day, day.beginning_of_day
        ).count(:id)
      end
    Sparkr.sparkline(runs_per_day)
  end

  def next_run_num
    if (latest = runs.order(num: :desc).limit(1).first)
      latest.num + 1
    else
      1
    end
  end

  def latest_runs(limit)
    runs.order(created_at: :desc).limit(limit)
  end

  def latest_run
    latest_runs(1).first
  end

  def latest_run_by_branch(branch)
    runs.where('branch = ?', branch)
        .order(created_at: :desc)
        .first
  end

  def branches
    if triggers.nil?
      []
    else
      triggers.gsub(/(\r)?\n/, '\n').split(/\\n/).uniq
    end
  end
end

app/controllers/pipelines_controller.rb
# frozen_string_literal: true

class PipelinesController < ApplicationController
  before_action :set_pipeline, only: %i[show edit update destroy run]

  # GET /pipelines
  # GET /pipelines.json
  def index
    @pipelines = Pipeline.all.includes(:runs)
  end

  # GET /pipelines/1
  # GET /pipelines/1.json
  def show; end

  # GET /pipelines/new
  def new
    @pipeline = Pipeline.new
  end

  # GET /pipelines/1/edit
  def edit; end

  # GET /pipelines/1/run?branch=master
  def run
    branch = params[:branch]
    @run = @pipeline.runs.create({
      num: @pipeline.next_run_num,
      branch: branch,
      triggered_by: 'user'
    })
    redirect_to "/pipelines/#{@pipeline.id}/runs/#{@run.id}"
  end

  # GET /pipelines/check
  def check
    CheckForBuildsJob.perform_later
    respond_to do |format|
      format.html { redirect_to pipelines_url, notice: 'Started a Pipeline scan.' }
      format.json { head :ok }
    end
  end

  # POST /pipelines
  # POST /pipelines.json
  def create
    @pipeline = Pipeline.new(pipeline_params)

    respond_to do |format|
      if @pipeline.save
        format.html { redirect_to @pipeline, notice: 'Pipeline was successfully created.' }
        format.json { render :show, status: :created, location: @pipeline }
      else
        format.html { render :new }
        format.json { render json: @pipeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pipelines/1
  # PATCH/PUT /pipelines/1.json
  def update
    respond_to do |format|
      if @pipeline.update(pipeline_params)
        format.html { redirect_to @pipeline, notice: 'Pipeline was successfully updated.' }
        format.json { render :show, status: :ok, location: @pipeline }
      else
        format.html { render :edit }
        format.json { render json: @pipeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pipelines/1
  # DELETE /pipelines/1.json
  def destroy
    @pipeline.destroy
    respond_to do |format|
      format.html { redirect_to pipelines_url, notice: 'Pipeline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pipeline
    @pipeline = Pipeline.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def pipeline_params
    params.require(:pipeline).permit(:name, :repo, :triggers, :domain)
  end
end

app/helpers/pipelines_helper.rb
# frozen_string_literal: true

module PipelinesHelper
  class PipelineConfiguration
    attr_reader :name, :run, :run_args, :remove_existing

    def initialize(path:, name:, run: true, run_args: '', remove_existing: false)
      @content = File.read(path)
      @name = try_get_value('name', name)
      @run = try_get_value('run', run)
      @run_args = try_get_value('run_args', run_args)
      @remove_existing = try_get_value('remove_existing', remove_existing)
    end

    def to_s
      <<~STR
        * name:             #{@name}
        * run:              #{@run}
        * run_args:         #{@run_args}
        * remove_existing:  #{@remove_existing}
      STR
    end

    private

    def try_get_value(key, default = nil)
      match = @content[/^[ ]*\#[ ]*#{key}\=.*$/]
      if match.nil?
        default
      else
        match[/\=.*/][1..]
      end
    end
  end
end

app/views/pipelines/_form.html.erb
<%= form_with(model: pipeline, local: true) do |form| %>
  <% if pipeline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pipeline.errors.count, "error") %> prohibited this pipeline from being saved:</h2>
      <ul>
        <% pipeline.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <strong><%= form.label :name %></strong>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <strong><%= form.label :repo %></strong>
    <%= form.text_field :repo %>
  </div>
  <div class="field">
    <strong><%= form.label :triggers %></strong>
    <br />
    <small>Write one branch name on each line.  Pipeline will automatically run on the specified branches when they are committed to.</small>
    <br />
    <%= form.text_area :triggers %>
  </div>
  <div class="field">
    <strong><%= form.label :domain %></strong>
    <br />
    <small>Secrets with the same <code>domain</code> will be automatically injected as build arguments and environment variables.</small>
    <br />
    <%= form.text_field :domain %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pipelines/edit.html.erb
<h1>Editing Pipeline</h1>

<%= render 'form', pipeline: @pipeline %>

<%= link_to 'Cancel', pipelines_path %>

app/views/pipelines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pipelines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Latest</th>
      <th>Activity</th>
      <th>Duration</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @pipelines.each do |pipeline| %>
      <tr>
        <td><b><%= pipeline.name %></b></td>
        <td><%= pipeline.runs.count > 0 ? pipeline.latest_run.status : 'Not yet run' %> <%= pipeline.runs.count > 0 ? "#{time_ago_in_words(pipeline.latest_run.created_at)} ago" : '' %></td>
        <td><code><%= pipeline.pretty_activity %></code></td>
        <td><%= pipeline.pretty_average_duration %></td>
        <td><%= link_to 'Show', pipeline, class: 'link-button' %></td>
        <td><%= link_to 'Edit', edit_pipeline_path(pipeline), class: 'link-button' %></td>
        <td><%= link_to 'Destroy', pipeline, method: :delete, data: { confirm: 'Are you sure?' }, class: 'link-button' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Pipeline', new_pipeline_path, class: 'link-button' %>
<%= link_to 'Manage Secrets', secrets_path, class: 'link-button' %>
<%= link_to 'Scan Pipelines', check_pipelines_path, class: 'link-button' %>

app/views/pipelines/new.html.erb
<h1>New Pipeline</h1>

<%= render 'form', pipeline: @pipeline %>

<%= link_to 'Cancel', pipelines_path %>

app/views/pipelines/run.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Running:</strong>
  <%= @pipeline.name %>
</p>
<p>
  <textarea>
    <%= @output %>
  </textarea>
</p>
<%= link_to 'Edit', edit_pipeline_path(@pipeline) %> |
<%= link_to 'Back', pipelines_path %>

app/views/pipelines/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @pipeline.name %> <%= link_to '⚙️', edit_pipeline_path(@pipeline) %></h1>
Last Month's Activity: <code><%= @pipeline.pretty_activity(days: 28) %></code>
<p>
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Started</th>
        <th>Status</th>
        <th>Git SHA</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @pipeline.runs.order(num: :desc).each do |run| %>
        <tr>
          <td><strong><%= run.num %></strong></td>
          <td><%= time_ago_in_words(run.created_at) %> ago</td>
          <td><%= run.status %></td>
          <td><code><%= run.commit_sha_short %></code></td>
          <td><%= link_to 'Show', "/pipelines/#{@pipeline.id}/runs/#{run.id}", class: 'link-button' %></td>
          <td><%= link_to 'Destroy', "/pipelines/#{@pipeline.id}/runs/#{run.id}", method: :delete, data: { confirm: 'Are you sure?' }, class: 'link-button' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</p>
<p>
  <% @pipeline.branches.each do |branch| %>
    <a href="<%= run_pipeline_path(@pipeline, branch: branch) %>" class="link-button"><i class="fa fa-play"></i> <%= branch %></a>
  <% end %>
  Domain: <code><%= @pipeline.domain %></code>
</p>
<%= link_to 'Back to Pipelines', pipelines_path %>